ssm:
  signer:
    user:
      name: ssm-admin
      key: user/ssm-admin
    admin:
      name: ssm-admin
      key: user/ssm-admin
  couchdb:
    url: http://localhost:5984
    username: couchdb
    password: couchdb
    serviceName: s2-sample-did
  chaincode:
    url: http://localhost:9090

s2:
  storming:
    enable: false

#debug: true