spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost/admin
      auto-index-creation: true

#debug: true
#logging:
#  level:
server:
  port: 2081
#    org.springframework.boot.rsocket: DEBUG